name: bowel
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - numpy=1.23.5
  - pandas=1.5.2
  - matplotlib=3.6.2
  - librosa=0.9.2
  - pip=22.3.1
  - scikit-learn=1.2.0
  - pyyaml=6.0
  - xlsxwriter=3.0.3
  - gitpython=3.1.29
  - xgboost=1.7.4
  - pip:
      - Flask==2.0.2
      - wandb==0.13.7
      - tensorflow==2.11.0
